apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: nginx:latest

          ports:
            - containerPort: 5000

          # ✅ Mount your Tekton PVC
          volumeMounts:
            - name: pipeline-storage
              mountPath: /workspace

      volumes:
        - name: pipeline-storage
          persistentVolumeClaim:
            claimName: pipelinerun-pvc
